config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: 'users/registrations', sessions: 'users/sessions',
                            omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :shows do
    post 'add_to_calendar', on: :member
    get 'search', on: :collection
  end

  root to: 'shows#index'
end

app/models/show.rb
class Show < ApplicationRecord
  scope :by_date, lambda {
    where('date >= ?', Date.today).order(:date)
  }

  def self.search(search_params, date_params = nil)
    if date_params
      Show.where(['date = ? and venue ILIKE ?', date_params, "%#{search_params}%"])
    else
      by_date.where('venue ILIKE ?', "%#{search_params}%")
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: %i[show edit update destroy add_to_calendar]
  before_action :search_params, only: %i[index]
  before_action :authenticate_user!, only: %i[add_to_calendar]
  before_action :token, only: %i[add_to_calendar]

  # GET /shows or /shows.json
  def index; end

  def search
    venue = params[:venue_input]
    if venue.present?
      @shows = ShowBuilderService.build_custom(SearchScraper.shows(venue))
      redirect_to root_path, notice: 'Shows found!'
    else
      redirect_to root_path notice: 'Please enter a venue'
    end
  end

  # GET /shows/1 or /shows/1.json
  def show; end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit; end

  # POST /shows or /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to show_url(@show), notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1 or /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to show_url(@show), notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1 or /shows/1.json
  def destroy
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_calendar
    response = CalendarClient.insert_event(current_user, @show)
    if response['status'] == 'confirmed'
      redirect_to root_path, notice: 'Show added to your calendar!'
    else
      redirect_to root_path, notice: 'Something went wrong. Please try again.'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_show
    @show = Show.find(params[:id])
  end

  def search_params
    @shows = if params[:date_input].present?
               Show.search(params[:search], params[:date_input])
             else
               Show.search(params[:search])
             end
  end

  def show_params
    params.require(:show).permit(:band, :doors, :venue, :date)
  end

  def token
    return unless current_user.access_token_expired?

    current_user.refresh_access_token!
    current_user.save!
  end
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/_form.html.erb
<%= form_with(model: show) do |form| %>
  <% if show.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
        <% show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :band, style: "display: block" %>
    <%= form.text_field :band %>
  </div>

  <div>
    <%= form.label :doors, style: "display: block" %>
    <%= form.text_field :doors %>
  </div>

  <div>
    <%= form.label :venue, style: "display: block" %>
    <%= form.text_field :venue %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/_show.html.erb
<div id="<%= dom_id show %>">
  <p>
    <strong>Band:</strong>
    <%= show.band %>
  </p>

  <p>
    <strong>Doors:</strong>
    <%= show.doors %>
  </p>

  <p>
    <strong>Venue:</strong>
    <%= show.venue %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= show.date %>
  </p>

</div>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Show this show", @show %> |
  <%= link_to "Back to shows", shows_path %>
</div>

app/views/shows/index.html.erb
<body>
  <div class="custom-cursor"></div>
  <% if current_user %>
    <h2> <%= current_user.name%> </h2>
    <%= button_to "Logout", destroy_user_session_path, data: {turbo: 'false'}, method: :delete %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, data: {turbo: 'false'} %>
    <%= link_to 'Sign Up', new_user_registration_path, data: {turbo: 'false'} %>
  <% end %>

  <%= form_tag search_shows_path, class:"search-venues", method: :get do %>
    <%= label_tag :venue_input, 'Search Venue by Name:' %>
    <%= text_field_tag :venue_input %>
    <%= submit_tag 'Search Venue', class: 'btn btn-primary' %>
  <% end %>
  <h1 class="">Current Events</h1>
  <%= form_tag shows_path, method: :get, class: "mb-4" do %>
    <div class="">
      <%= select_tag :search, options_for_select(Show.pluck(:venue).uniq),  prompt: "Venue", class: "" %>
      <%= date_field_tag :date_input, nil, class: "" %>
      <%= submit_tag "Search", class: "" %>
    </div>
  <% end %>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <% @shows.each do |show| %>
      <div class="rounded-lg shadow-lg bg-gradient-to-br from-purple-500 to-pink-500">
        <div class="p-6">
          <h3 class="text-lg font-medium text-gray-900 mb-2"><%= show.band%></h3>
          <p class="text-gray-800 mb-4"><%= show.venue %></p>
          <p class="text-gray-600 mb-4"><%= show.date.strftime("%A, %B %d, %Y") %></p>
          <p class="text-gray-800 mb-4"><%= show.doors %></p>
          <% if !show.tickets.blank? %>
            <p class="text-grey-800 mb-4" <a href="<% show.tickets%>" class="">tickets</a> </p>
          <% end %>
          <% if current_user %>
            <%= button_to 'Add to Calendar', add_to_calendar_show_path(show), method: :post %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <script src="/assets/mouse.js"></script>
</body>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render "form", show: @show %>

<br>

<div>
  <%= link_to "Back to shows", shows_path %>
</div>

app/views/shows/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @show %>

<div>
  <%= link_to "Edit this show", edit_show_path(@show) %> |
  <%= link_to "Back to shows", shows_path %>

  <%= button_to "Destroy this show", @show, method: :delete %>
</div>